version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: bank_database
    restart: always
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5430:5432"

  app:
    build: .
    container_name: bank_app
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bank
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      JWT_SECRET_KEY: 57e945edd50c0da7c3695a5f0a2c7beca67ddfe7875fa84b602b6f5e8e24bea3
      SERVER_PORT: 8000
    ports:
      - "8000:8000"
    command: ["java", "-jar", "app.jar"]

volumes:
  postgres_data:
