# 
# docker-compose.yml — определяет сервисы для разработки и тестирования.

version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: bank_database
    restart: always
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5430:5432"


volumes:
  postgres_data:

